inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - .irbrc

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 122

Metrics/AbcSize:
  Exclude:
    - test/**/*.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb
